apiVersion: apps/v1
kind: Deployment
metadata:  
    name: ms-regioes-api
spec:  
    selector:    
        matchLabels:      
          app: ms-regioes-api  
    template:    
        metadata:      
          labels:        
            app: ms-regioes-api    
        spec:      
          containers:      
          - name: ms-regioes-api        
            image: regioesapi        
            imagePullPolicy: IfNotPresent        
            env:          
              - name:  PORT            
                value: "8080"        
            resources:          
              limits:            
                memory: "64Mi"            
                cpu: "128m"        
            ports:        
            - containerPort: 8080          
              name: http 
---
apiVersion: v1
kind: Service
metadata:  
   name: ms-regioes-api
spec:  
   selector:    
      app: ms-regioes-api  
   ports:  
   - port: 80    
   targetPort: http