# Deploy do postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresregiao
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: postgresregiao
  template:
    metadata:
      labels:
        app: postgresregiao
    spec:
      containers:
        - name: postgresregiao
          image: postgres:13.1
          env:
          - name: POSTGRES_PASSWORD
            value: Floripa102030
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: regioesdatabase
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresregiao
spec: 
  selector:
    app: postgresregiao
  ports:
    - port: 5432
---
# Deploy da Aplicação Web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msregiaoapipod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msregiaoapipod
  template:
    metadata:
      labels:
        app: msregiaoapipod
    spec: 
      containers:
      - name: msregiaoapipod
        image: fabaofloripa/regioes.api:latest
        env:
        - name: ConnectionStringPostgres
          value: "Host=postgresregiao;Database=regioesdatabase;Username=postgres;Password=Floripa102030"
        ports:
          - containerPort: 8080
  
---

apiVersion: v1
kind: Service
metadata:
  name: msregiaoapipod-service  
spec:
  selector:
    app: msregiaoapipod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
