name: CI/CD Pipeline MsRegiao FIAP API

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin


      - name: Build and Push Docker Image
        run: |
          docker build -t fabaofloripa/regioes.api:latest .
          docker push fabaofloripa/regioes.api:latest
